version: '3.8'

services:
  app:
    build: .
    container_name: e-learning-app
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/E-learning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_USER_NAME: jay
      SPRING_SECURITY_USER_PASSWORD: jay
      RAZORPAY_KEY: rzp_test_i5W2KHSQgUl6Pw
      RAZORPAY_SECRET: AMOO4qQeNvqKTz53kwzDiVVK
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: E-learning
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
